empresasBundle\Entity\empresa:
    type: entity
    table: null
    repositoryClass: empresasBundle\Repository\empresaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        direccion:
            type: string
            length: 255
        cp:
            type: integer
        telefono1:
            type: integer
        telefono2:
            type: integer
        fechaCreacion:
            type: date
            column: fecha_creacion
    lifecycleCallbacks: {  }
