users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /users/

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

fct:
    resource: "@FCTBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /users/logout
