# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        UsersBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 1234
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:

            pattern: ^/admin
            http_basic: ~

        users:
            pattern: ^/users
            anonymous: ~

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
