users_homepage:
    path:     /
    defaults: { _controller: UsersBundle:User:users}


registration:
    path:     /register
    defaults: { _controller: UsersBundle:User:register}


login:
    path:     /login
    defaults: { _controller: UsersBundle:User:login}
